// <auto-generated />
namespace LandingPage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_role));
        
        string IMigrationMetadata.Id
        {
            get { return "202006102024402_update_role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
